# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import cv2

from PyQt5 import QtCore, QtGui, QtWidgets
from Question1 import Image_Processing
from Question2 import Image_Smoothing
from Question3 import Edge_Detection


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(987, 425)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # groupBox_1
        self.groupBox_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_1.setGeometry(QtCore.QRect(20, 20, 201, 361))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.groupBox_1.setFont(font)
        self.groupBox_1.setObjectName("groupBox_1")

        self.Button1_1 = QtWidgets.QPushButton(self.groupBox_1)
        self.Button1_1.setGeometry(QtCore.QRect(20, 60, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setKerning(True)
        self.Button1_1.setFont(font)
        self.Button1_1.setAutoFillBackground(False)
        self.Button1_1.setObjectName("Button1_1")
        # self.Btn = Image_Processing.Question1_1(self)
        self.Button1_1.clicked.connect(lambda: Image_Processing.Load_Image(self))

        self.Button1_2 = QtWidgets.QPushButton(self.groupBox_1)
        self.Button1_2.setGeometry(QtCore.QRect(20, 130, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.Button1_2.setFont(font)
        self.Button1_2.setObjectName("Button1_2")
        self.Button1_2.clicked.connect(lambda: Image_Processing.Color_Separation(self))

        self.Button1_3 = QtWidgets.QPushButton(self.groupBox_1)
        self.Button1_3.setGeometry(QtCore.QRect(20, 200, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.Button1_3.setFont(font)
        self.Button1_3.setObjectName("Button1_3")
        self.Button1_3.clicked.connect(lambda: Image_Processing.Image_Flipping(self))

        self.Button1_4 = QtWidgets.QPushButton(self.groupBox_1)
        self.Button1_4.setGeometry(QtCore.QRect(20, 270, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.Button1_4.setFont(font)
        self.Button1_4.setObjectName("Button1_4")
        self.Button1_4.clicked.connect(lambda: Image_Processing.Blending(self))

        # groupBox_2
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(240, 20, 201, 361))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")

        self.Button2_1 = QtWidgets.QPushButton(self.groupBox_2)
        self.Button2_1.setGeometry(QtCore.QRect(20, 60, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.Button2_1.setFont(font)
        self.Button2_1.setAutoFillBackground(False)
        self.Button2_1.setObjectName("Button2_1")
        self.Button2_1.clicked.connect(lambda: Image_Smoothing.Median_Filter(self))

        self.Button2_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.Button2_2.setGeometry(QtCore.QRect(20, 130, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.Button2_2.setFont(font)
        self.Button2_2.setObjectName("Button2_2")
        self.Button2_2.clicked.connect(lambda: Image_Smoothing.Gaussian_Blur(self))

        self.Button2_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.Button2_3.setGeometry(QtCore.QRect(20, 200, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.Button2_3.setFont(font)
        self.Button2_3.setObjectName("Button2_3")
        self.Button2_3.clicked.connect(lambda: Image_Smoothing.Bilateral_Filter(self))

        # groupBox_3
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(460, 20, 201, 361))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")

        self.Button3_1 = QtWidgets.QPushButton(self.groupBox_3)
        self.Button3_1.setGeometry(QtCore.QRect(20, 60, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.Button3_1.setFont(font)
        self.Button3_1.setAutoFillBackground(False)
        self.Button3_1.setObjectName("Button3_1")
        self.Button3_1.clicked.connect(lambda: Edge_Detection.Gaussian_nocv(self))

        self.Button3_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.Button3_2.setGeometry(QtCore.QRect(20, 130, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.Button3_2.setFont(font)
        self.Button3_2.setObjectName("Button3_2")
        self.Button3_2.clicked.connect(lambda: Edge_Detection.Sobel_X(self))

        self.Button3_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.Button3_3.setGeometry(QtCore.QRect(20, 200, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.Button3_3.setFont(font)
        self.Button3_3.setObjectName("Button3_3")
        self.Button3_3.clicked.connect(lambda: Edge_Detection.Sobel_Y(self))

        self.Button3_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.Button3_4.setGeometry(QtCore.QRect(20, 270, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.Button3_4.setFont(font)
        self.Button3_4.setObjectName("Button3_4")
        self.Button3_4.clicked.connect(lambda: Edge_Detection.Magnitude(self))

        # groupBox_4
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(680, 20, 281, 361))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")

        self.Button4 = QtWidgets.QPushButton(self.groupBox_4)
        self.Button4.setGeometry(QtCore.QRect(60, 270, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.Button4.setFont(font)
        self.Button4.setObjectName("Button4")
        self.Button4.clicked.connect(self.Transform)

        self.label4_1 = QtWidgets.QLabel(self.groupBox_4)
        self.label4_1.setGeometry(QtCore.QRect(20, 61, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.label4_1.setFont(font)
        self.label4_1.setObjectName("label4_1")

        self.label4_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label4_2.setGeometry(QtCore.QRect(20, 110, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.label4_2.setFont(font)
        self.label4_2.setObjectName("label4_2")

        self.label4_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label4_3.setGeometry(QtCore.QRect(20, 160, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.label4_3.setFont(font)
        self.label4_3.setObjectName("label4_3")

        self.label4_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label4_4.setGeometry(QtCore.QRect(20, 210, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.label4_4.setFont(font)
        self.label4_4.setObjectName("label4_4")

        self.lineEdit4_1 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit4_1.setGeometry(QtCore.QRect(100, 60, 113, 20))
        self.lineEdit4_1.setObjectName("lineEdit4_1")

        self.lineEdit4_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit4_2.setGeometry(QtCore.QRect(100, 110, 113, 20))
        self.lineEdit4_2.setObjectName("lineEdit4_2")

        self.lineEdit4_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit4_3.setGeometry(QtCore.QRect(100, 160, 113, 20))
        self.lineEdit4_3.setObjectName("lineEdit4_3")

        self.lineEdit4_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit4_4.setGeometry(QtCore.QRect(100, 210, 113, 20))
        self.lineEdit4_4.setObjectName("lineEdit4_4")

        self.label_1 = QtWidgets.QLabel(self.groupBox_4)
        self.label_1.setGeometry(QtCore.QRect(220, 60, 51, 21))
        self.label_1.setObjectName("label_1")

        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(220, 160, 51, 21))
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(220, 210, 51, 21))
        self.label_3.setObjectName("label_3")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 987, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # Question4
    def Transform(self):
        rotation = self.lineEdit4_1.text()
        scaling = self.lineEdit4_2.text()
        Tx = self.lineEdit4_3.text()
        Ty = self.lineEdit4_4.text()
        # print(rotation, scaling, Tx, Ty)

        image = cv2.imread('./Dataset_opencvdl/Q4_Image/Parrot.png')  # image.shape=(600, 900, 3)
        # cv2.namedWindow('Original Image')
        # cv2.imshow('Original Image', image)

        center = ((image.shape[1] // 2 + float(Tx)), (image.shape[0] // 2 - float(Ty)))
        rot_mat = cv2.getRotationMatrix2D(center, float(rotation), float(scaling))
        rot_dst = cv2.warpAffine(image, rot_mat, (image.shape[1], image.shape[0]))

        cv2.namedWindow('Image RST')
        cv2.imshow('Image RST', rot_dst)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_1.setTitle(_translate("MainWindow", "1. Image Processing"))
        self.Button1_1.setText(_translate("MainWindow", "1.1 Load Image      "))
        self.Button1_2.setText(_translate("MainWindow", "1.2 Color seperation"))
        self.Button1_3.setText(_translate("MainWindow", "1.3 Image Flipping  "))
        self.Button1_4.setText(_translate("MainWindow", "1.4 Blending        "))
        self.groupBox_2.setTitle(_translate("MainWindow", "2. Image Smoothing"))
        self.Button2_1.setText(_translate("MainWindow", "2.1 Median Filter   "))
        self.Button2_2.setText(_translate("MainWindow", "2.2 Gaussian Blur   "))
        self.Button2_3.setText(_translate("MainWindow", "2.3 Bilateral Filter"))
        self.groupBox_3.setTitle(_translate("MainWindow", "3. Edge Detection"))
        self.Button3_1.setText(_translate("MainWindow", "3.1 Gaussian Blur"))
        self.Button3_2.setText(_translate("MainWindow", "3.2 Sobel X     "))
        self.Button3_3.setText(_translate("MainWindow", "3.3 Sobel Y     "))
        self.Button3_4.setText(_translate("MainWindow", "3.4 Magnitude   "))
        self.groupBox_4.setTitle(_translate("MainWindow", "4. Transformation"))
        self.Button4.setText(_translate("MainWindow", "4. Transformation"))
        self.label4_1.setText(_translate("MainWindow", "Rotation: "))
        self.label4_2.setText(_translate("MainWindow", "Scaling: "))
        self.label4_3.setText(_translate("MainWindow", "Tx: "))
        self.label4_4.setText(_translate("MainWindow", "Ty: "))
        self.label_1.setText(_translate("MainWindow", "deg"))
        self.label_2.setText(_translate("MainWindow", "pixel"))
        self.label_3.setText(_translate("MainWindow", "pixel"))
